server:
  port: 8083
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
      
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/trip
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
       ddl-auto: update
       
  application:
    name: TASK-SERVICE

